"""Debate-bait topic pool — opinion questions engineered to split comments 50/50.

Comment arguments are the algorithm's favorite engagement signal. Every topic is
deliberately inside the safety rails: culture and behavior only — no politics,
religion, tragedy, protected classes, or named individuals (the trend_sources
denylist applies to every entry; test-enforced).

Each topic: {key, topic, stance_seed, binary_cta}
- key: unique kebab-case slug (e.g. "discipline-vs-talent")
- topic: the debate subject (feeds story_writer's debate mode)
- stance_seed: the contrarian position the content argues
- binary_cta: the comment-splitting ask (used as caption CTA or first comment)
"""

DEBATE_TOPICS = [
    {"key": "discipline-vs-talent",
     "topic": "discipline vs talent",
     "stance_seed": "Talent is an excuse invented by people who quit early.",
     "binary_cta": "Discipline or talent — which actually got you here? Comments."},
    {"key": "the-9-5-debate",
     "topic": "the 9-5 debate",
     "stance_seed": "The 9-5 isn't the trap. Spending it half-asleep is.",
     "binary_cta": "Is the 9-5 a trap or a training ground? Pick a side."},
    {"key": "phones-at-dinner",
     "topic": "phones at dinner",
     "stance_seed": "Your phone isn't stealing your attention. You're donating it.",
     "binary_cta": "Phones at the table — harmless or disrespect? Argue."},
    {"key": "morning-routines",
     "topic": "morning routines",
     "stance_seed": "The 5am club is theater. Winning your first hour matters; the clock doesn't.",
     "binary_cta": "5am club: life-changing or performative? Comments."},
    {"key": "motivation-vs-systems",
     "topic": "motivation vs systems",
     "stance_seed": "Motivation is weather. Systems are climate.",
     "binary_cta": "Motivation or systems — what do you actually run on?"},
    {"key": "comfort-as-the-enemy",
     "topic": "comfort as the enemy",
     "stance_seed": "Your comfort zone is the most expensive place you'll ever live.",
     "binary_cta": "Agree or disagree: comfort is costing you more than failure."},
    {"key": "hustle-culture",
     "topic": "hustle culture",
     "stance_seed": "Hustle without direction is just anxiety with better branding.",
     "binary_cta": "Hustle culture: fuel or poison? Pick one."},
    {"key": "ai-and-jobs",
     "topic": "AI and jobs",
     "stance_seed": "AI won't take your job. Refusing to think will.",
     "binary_cta": "Is AI a threat to you or a tool for you? Comments."},
    {"key": "gym-vs-therapy",
     "topic": "gym vs therapy",
     "stance_seed": "The gym fixes what talking can't. Talking fixes what lifting can't.",
     "binary_cta": "Gym or therapy — which changed you more?"},
    {"key": "dating-apps",
     "topic": "dating apps",
     "stance_seed": "Dating apps didn't ruin romance. Outsourcing your standards did.",
     "binary_cta": "Dating apps: tool or trap? Argue below."},
    {"key": "soft-parenting",
     "topic": "soft parenting",
     "stance_seed": "Kids don't need easier lives. They need harder examples.",
     "binary_cta": "Strict or gentle parenting — which builds stronger adults?"},
    {"key": "money-mindset",
     "topic": "money mindset",
     "stance_seed": "Money doesn't change people. It removes their excuses for who they were.",
     "binary_cta": "Does money change people — or reveal them? Comments."},
    {"key": "college-worth",
     "topic": "college worth",
     "stance_seed": "The degree isn't the scam. Sleepwalking through it is.",
     "binary_cta": "Is college still worth it in 2026? Pick a side."},
    {"key": "screen-time-for-focus",
     "topic": "screen time for focus",
     "stance_seed": "You don't have an attention problem. You have an exit habit.",
     "binary_cta": "Could you do 24 hours phoneless? Honest answers only."},
    {"key": "quiet-quitting",
     "topic": "quiet quitting",
     "stance_seed": "Doing the minimum isn't rebellion. It's rehearsal for mediocrity.",
     "binary_cta": "Quiet quitting: self-respect or self-sabotage?"},
    {"key": "cold-showers",
     "topic": "cold showers",
     "stance_seed": "The cold shower isn't the point. Keeping a promise to yourself at 6am is.",
     "binary_cta": "Cold showers: discipline builder or placebo? Argue."},
    {"key": "friends-and-ambition",
     "topic": "friends and ambition",
     "stance_seed": "Your circle isn't holding you back. Your loyalty to their comfort is.",
     "binary_cta": "Can you outgrow friends without abandoning them? Comments."},
    {"key": "reading-vs-doing",
     "topic": "reading vs doing",
     "stance_seed": "Another book won't fix you. Applying page one would.",
     "binary_cta": "Self-help books: growth or procrastination? Pick one."},
    {"key": "work-life-balance",
     "topic": "work-life balance",
     "stance_seed": "Balance is a myth sold to people afraid of seasons.",
     "binary_cta": "Work-life balance: real goal or pretty lie? Comments."},
    {"key": "talent-shows-and-shortcuts",
     "topic": "talent shows and shortcuts",
     "stance_seed": "Overnight success is a decade nobody watched.",
     "binary_cta": "Is there such a thing as an earned shortcut? Argue."},
    {"key": "gap-years",
     "topic": "gap years",
     "stance_seed": "A gap year without a plan is just a very long weekend.",
     "binary_cta": "Gap year: growth or drift? Pick a side."},
    {"key": "side-hustles",
     "topic": "side hustles",
     "stance_seed": "Your side hustle is either a second job or an escape plan. Not both.",
     "binary_cta": "Side hustles: freedom or burnout with extra steps?"},
    {"key": "minimalism",
     "topic": "minimalism",
     "stance_seed": "Owning less won't fix wanting more.",
     "binary_cta": "Minimalism: wisdom or aesthetic? Comments."},
    {"key": "productivity-apps",
     "topic": "productivity apps",
     "stance_seed": "You don't need a new app. You need to stop negotiating with yourself.",
     "binary_cta": "Productivity apps: helping you or hiding you? Argue."},
    {"key": "early-birds-vs-night-owls",
     "topic": "early birds vs night owls",
     "stance_seed": "It's not about when you wake. It's about what you refuse to skip.",
     "binary_cta": "Early bird or night owl — who actually wins? Comments."},
    {"key": "journaling",
     "topic": "journaling",
     "stance_seed": "Journaling isn't soft. Facing your own sentences is combat.",
     "binary_cta": "Journaling: powerful or overhyped? Pick one."},
    {"key": "social-media-detox",
     "topic": "social media detox",
     "stance_seed": "You don't need a detox. You need a reason to be somewhere else.",
     "binary_cta": "Could you delete one app for 30 days? Which one?"},
    {"key": "failure-as-teacher",
     "topic": "failure as teacher",
     "stance_seed": "Failure teaches nothing. Reflection on failure teaches everything.",
     "binary_cta": "Does failure actually teach — or just hurt? Argue."},
    {"key": "nice-vs-kind",
     "topic": "nice vs kind",
     "stance_seed": "Nice avoids conflict. Kind tells you the truth anyway.",
     "binary_cta": "Would you rather be liked or respected? Honest answers."},
    {"key": "waiting-for-ready",
     "topic": "waiting for ready",
     "stance_seed": "Ready is a feeling you get AFTER you start. Never before.",
     "binary_cta": "Agree or disagree: nobody has ever actually felt ready."},
    {"key": "multitasking",
     "topic": "multitasking",
     "stance_seed": "Multitasking is doing several things badly and calling it busy.",
     "binary_cta": "Can anyone truly multitask? Defend your answer."},
    {"key": "new-year-resolutions",
     "topic": "new year resolutions",
     "stance_seed": "January 1st is for people who need permission. Today is for people who don't.",
     "binary_cta": "Resolutions: useful ritual or annual lie? Comments."},
    {"key": "comparison-culture",
     "topic": "comparison culture",
     "stance_seed": "Comparison isn't the thief of joy. It's the tax on aimlessness.",
     "binary_cta": "Is comparing yourself to others ever useful? Argue."},
    {"key": "toxic-positivity",
     "topic": "toxic positivity",
     "stance_seed": "Forced positivity is just denial with better lighting.",
     "binary_cta": "Good vibes only: healthy or delusional? Pick a side."},
    {"key": "sleep-vs-grind",
     "topic": "sleep vs grind",
     "stance_seed": "Sacrificing sleep to grind is borrowing focus at loan-shark rates.",
     "binary_cta": "Team 8-hours or team grind — who's actually right?"},
    {"key": "advice-culture",
     "topic": "advice culture",
     "stance_seed": "Most advice is autobiography wearing a disguise.",
     "binary_cta": "Best advice you ever IGNORED — and were right to? Comments."},
]


def pick_debate(row_number: int | None, exclude: frozenset = frozenset()) -> dict:
    """Deterministic debate pick; skips recently-used keys (spec 3)."""
    n = row_number or 0
    base = n % len(DEBATE_TOPICS)
    for step in range(len(DEBATE_TOPICS)):
        cand = DEBATE_TOPICS[(base + step) % len(DEBATE_TOPICS)]
        if cand.get("key") not in exclude:
            return cand
    return DEBATE_TOPICS[base]
