"""Weird-story share magnets — TRUE bizarre philosophy history + modern hypotheticals.

The strongest send-to-a-friend trigger on Instagram is "no way this is real"
energy. Pool 1 is REAL, historically attested anecdotes from ancient philosophy
(every capsule's source_note names the ancient source — mostly Diogenes
Laertius' *Lives of Eminent Philosophers*, Plato, Plutarch). No invented facts.
Pool 2 is bizarre modern hypotheticals, flagged hypothetical=True so copy never
presents them as fact.

Capsule shape: {hook_fact, escalation, source_note, lesson_theme, send_cta}
Hypothetical shape: same + hypothetical=True.
"""

WEIRD_CAPSULES = [
    {"hook_fact": "This philosopher lived in a giant ceramic jar in the middle of Athens.",
     "escalation": "Diogenes owned one cup — then saw a boy drink with his hands and threw the cup away. When Alexander the Great, the most powerful man alive, offered him anything he wanted, he said: 'Move. You're blocking my sunlight.'",
     "source_note": "Diogenes Laertius, Lives of Eminent Philosophers VI",
     "lesson_theme": "freedom through wanting less",
     "send_cta": "Send this to the friend who needs nothing and fears no one."},
    {"hook_fact": "Socrates once stood frozen in one spot for 24 hours straight — thinking.",
     "escalation": "During a military campaign, soldiers dragged their bedding outside to watch him. He stood through the night, solved whatever gripped his mind, greeted the sunrise, and walked off like nothing happened.",
     "source_note": "Plato, Symposium 220c-d",
     "lesson_theme": "depth of focus",
     "send_cta": "Send this to someone who can't sit with one thought for 5 minutes."},
    {"hook_fact": "A man carried a lit lamp through Athens in broad daylight.",
     "escalation": "Asked what he was doing, Diogenes said: 'Looking for an honest human.' He held the lamp to people's faces all day. He reported finding none.",
     "source_note": "Diogenes Laertius, Lives VI.41",
     "lesson_theme": "honesty is rarer than daylight",
     "send_cta": "Send this to the most honest person you know. They'll get it."},
    {"hook_fact": "Pythagoras — the triangle guy — banned his followers from touching beans.",
     "escalation": "The mathematical genius ran a secret society with rules like 'never eat beans' and 'don't pick up what has fallen.' Ancient sources say he'd rather be caught than cross a bean field.",
     "source_note": "Diogenes Laertius, Lives VIII; Iamblichus",
     "lesson_theme": "even geniuses guard strange disciplines",
     "send_cta": "Send this to your smartest friend with the weirdest habits."},
    {"hook_fact": "Zeno lost everything in a shipwreck — then thanked the sea.",
     "escalation": "A wealthy merchant, ruined in one storm, washed up in Athens, wandered into a bookshop, and founded Stoicism. He later said: 'I made a prosperous voyage when I suffered shipwreck.'",
     "source_note": "Diogenes Laertius, Lives VII.4",
     "lesson_theme": "catastrophe as redirection",
     "send_cta": "Send this to someone whose plan A just collapsed."},
    {"hook_fact": "An ancient philosopher reportedly died laughing at his own joke.",
     "escalation": "Chrysippus, who wrote 705 books of rigorous logic, saw a donkey eating figs, told someone to give it wine to wash them down, and — the ancient account says — laughed until he died.",
     "source_note": "Diogenes Laertius, Lives VII.185",
     "lesson_theme": "seriousness and joy are not opposites",
     "send_cta": "Send this to the friend whose laugh could kill them."},
    {"hook_fact": "Socrates was ugly. Famously, insultingly ugly — and he agreed.",
     "escalation": "Snub nose, bulging eyes, a walk people mocked. The most beautiful minds in Athens followed him anyway. He joked his face proved wisdom lives somewhere other than looks.",
     "source_note": "Plato, Theaetetus 143e; Xenophon, Symposium",
     "lesson_theme": "substance beats appearance",
     "send_cta": "Send this to someone who forgets their face isn't their worth."},
    {"hook_fact": "Diogenes was sold into slavery — and interviewed his buyers.",
     "escalation": "Captured by pirates and put on the auction block, he pointed at a buyer and said 'Sell me to him. He needs a master.' He then ran the man's household and educated his sons.",
     "source_note": "Diogenes Laertius, Lives VI.74",
     "lesson_theme": "inner freedom no one can sell",
     "send_cta": "Send this to the freest person you know."},
    {"hook_fact": "Epictetus' owner twisted his leg. The philosopher calmly narrated it breaking.",
     "escalation": "'You will break it,' the enslaved philosopher said. When it snapped: 'Did I not tell you?' He limped for life — and taught emperors that no one can chain a mind.",
     "source_note": "Origen, Contra Celsum VII.53 (ancient tradition)",
     "lesson_theme": "what remains yours under force",
     "send_cta": "Send this to someone going through what they didn't choose."},
    {"hook_fact": "A Roman emperor kept a private journal begging himself to get out of bed.",
     "escalation": "The most powerful man on Earth wrote, to no audience: 'At dawn, when you have trouble getting up — say: I am rising to do the work of a human being.' He struggled like you. Every morning.",
     "source_note": "Marcus Aurelius, Meditations V.1",
     "lesson_theme": "even emperors negotiate with the alarm",
     "send_cta": "Send this to the friend who snoozed four times today."},
    {"hook_fact": "Diogenes attended a lecture, then plucked a chicken.",
     "escalation": "Plato defined a human as a 'featherless biped.' Diogenes burst into the academy holding a plucked chicken and announced: 'Behold — Plato's human!' Plato amended the definition.",
     "source_note": "Diogenes Laertius, Lives VI.40",
     "lesson_theme": "test grand claims against reality",
     "send_cta": "Send this to the friend who destroys bad arguments for fun."},
    {"hook_fact": "Thales fell into a well while staring at the stars.",
     "escalation": "The first philosopher of the West, mocked by a servant girl for studying the sky while missing the ground. Then he used his star knowledge to corner the olive-press market and got rich — to prove philosophers could.",
     "source_note": "Plato, Theaetetus 174a; Aristotle, Politics I.11",
     "lesson_theme": "vision needs footing",
     "send_cta": "Send this to your most head-in-the-clouds friend."},
    {"hook_fact": "Cato walked bareheaded in storms and wore no shoes in Rome.",
     "escalation": "One of Rome's richest senators deliberately practiced poverty — bad clothes, hard ground, plain food — so that if fortune ever took everything, it would find him already trained.",
     "source_note": "Plutarch, Life of Cato; Seneca, Letters 18",
     "lesson_theme": "rehearse loss to defeat fear",
     "send_cta": "Send this to someone terrified of losing what they have."},
    {"hook_fact": "Socrates heard a voice in his head his whole life — and obeyed it.",
     "escalation": "He called it his daimonion. It never told him what to do — only what NOT to do. It stayed silent the day he walked into the trial that killed him. He took the silence as approval.",
     "source_note": "Plato, Apology 31d, 40a-c",
     "lesson_theme": "the quiet inner no",
     "send_cta": "Send this to someone who ignored their gut and regrets it."},
    {"hook_fact": "A philosopher begged statues for money — on purpose, in public.",
     "escalation": "Asked why, Diogenes said: 'To practice being refused.' He rehearsed rejection daily until no human 'no' could touch him.",
     "source_note": "Diogenes Laertius, Lives VI.49",
     "lesson_theme": "rejection-proofing yourself",
     "send_cta": "Send this to the friend who's scared to ask."},
    {"hook_fact": "Seneca — one of Rome's richest men — scheduled days of poverty.",
     "escalation": "Silk-wealthy, he'd set aside days to eat scraps and wear rags, asking one question the whole time: 'Is THIS what I was afraid of?' The answer kept being no.",
     "source_note": "Seneca, Letters to Lucilius 18",
     "lesson_theme": "fear shrinks when rehearsed",
     "send_cta": "Send this to someone whose fear is running the show."},
    {"hook_fact": "Socrates refused to escape prison — his friends had already bribed the guards.",
     "escalation": "The door was effectively open. Crito begged. Socrates asked one question: 'If I flee the laws when they turn against me, was I ever just — or only lucky?' He stayed. He drank the hemlock.",
     "source_note": "Plato, Crito",
     "lesson_theme": "principles cost or they're decoration",
     "send_cta": "Send this to the most principled person you know."},
    {"hook_fact": "Heraclitus said you can't step in the same river twice — then chose to live in a stable.",
     "escalation": "The philosopher of change despised the crowds of Ephesus, retreated to the mountains, and reportedly lived on grasses and plants rather than trade his solitude for their politics.",
     "source_note": "Diogenes Laertius, Lives IX",
     "lesson_theme": "everything flows; choose your current",
     "send_cta": "Send this to the friend who's never the same person twice."},
    {"hook_fact": "Aristippus let a king spit in his face — and shrugged.",
     "escalation": "'Fishermen endure seawater to catch small fish,' he said. 'I endure spray to catch a big one.' The same man, watching Diogenes wash lentils: 'If you flattered kings, you wouldn't eat lentils.' Diogenes: 'If you ate lentils, you wouldn't flatter kings.'",
     "source_note": "Diogenes Laertius, Lives II.67-68",
     "lesson_theme": "every lifestyle has a price tag",
     "send_cta": "Send this to someone deciding what they're willing to pay."},
    {"hook_fact": "Anaxagoras was told his sons had died. He said: 'I knew they were mortal.'",
     "escalation": "Not coldness — preparation. He'd spent years rehearsing the truth everyone avoids, so grief found him standing. The ancients called it the discipline nobody wants until the day everybody needs it.",
     "source_note": "Diogenes Laertius, Lives II.13; Cicero, Tusculan Disputations III",
     "lesson_theme": "premeditatio malorum",
     "send_cta": "Send this to someone strong enough to hear it."},
]

WEIRD_HYPOTHETICALS = [
    {"hook_fact": "If your phone could testify about your week, would you delete it before the trial?",
     "escalation": "Every unlock logged. Every 2am scroll on record. Every 'just five minutes' entered as evidence. The prosecution rests.",
     "source_note": "hypothetical",
     "lesson_theme": "your attention is the testimony",
     "send_cta": "Send this to the friend whose phone would snitch hardest.",
     "hypothetical": True},
    {"hook_fact": "Imagine you met yourself from 5 years ago — and they refused to shake your hand.",
     "escalation": "Not because you failed. Because you quietly gave up the exact things they were fighting for, and called it 'being realistic.'",
     "source_note": "hypothetical",
     "lesson_theme": "audit the trade-offs",
     "send_cta": "Send this to someone their younger self would still be proud of.",
     "hypothetical": True},
    {"hook_fact": "Suppose every complaint you spoke cost you one hour of life.",
     "escalation": "Some people in your group chat would be gone by Thursday. The Stoics ran this exact accounting — they just used attention instead of hours.",
     "source_note": "hypothetical",
     "lesson_theme": "complaint is spent attention",
     "send_cta": "Send this to the group chat. You know which one.",
     "hypothetical": True},
    {"hook_fact": "What if you woke up tomorrow with only the things you thanked someone for yesterday?",
     "escalation": "Most people would wake up with nothing but wifi and coffee. The ancients called gratitude an inventory, not a feeling.",
     "source_note": "hypothetical",
     "lesson_theme": "gratitude as inventory",
     "send_cta": "Send this to someone you never actually thanked.",
     "hypothetical": True},
    {"hook_fact": "Imagine a mirror that showed your habits instead of your face.",
     "escalation": "You'd see the 6 hours of scrolling standing behind you. The workout you skipped sitting on your shoulders. Nobody would own one. Everybody needs one.",
     "source_note": "hypothetical",
     "lesson_theme": "habits are the real reflection",
     "send_cta": "Send this to the friend brave enough to look.",
     "hypothetical": True},
    {"hook_fact": "If silence cost money, how much would your mind owe by noon?",
     "escalation": "Every notification answered like a debt collector. The Stoics ran the ledger differently: attention paid IN is the only interest that compounds.",
     "source_note": "hypothetical",
     "lesson_theme": "attention as currency",
     "send_cta": "Send this to someone who hasn't had a quiet hour in weeks.",
     "hypothetical": True},
]


def pick_weird(row_number: int | None) -> dict:
    """Deterministic weird pick: 3 true capsules to every 1 hypothetical."""
    n = row_number or 0
    if n % 4 == 3:
        return WEIRD_HYPOTHETICALS[(n // 4) % len(WEIRD_HYPOTHETICALS)]
    idx = (n - n // 4) % len(WEIRD_CAPSULES)
    return WEIRD_CAPSULES[idx]
