"""Weird-story share magnets — TRUE bizarre philosophy history + modern hypotheticals.

The strongest send-to-a-friend trigger on Instagram is "no way this is real"
energy. Pool 1 is REAL, historically attested anecdotes from ancient philosophy
(every capsule's source_note names the ancient source — mostly Diogenes
Laertius' *Lives of Eminent Philosophers*, Plato, Plutarch, Seneca). No
invented facts. Pool 2 is bizarre modern hypotheticals, flagged
hypothetical=True so copy never presents them as fact.

Capsule shape: {key, hook_fact, escalation, source_note, lesson_theme, send_cta}
Hypothetical shape: same + hypothetical=True. `key` is a unique kebab-case
slug across both pools (used for dedup/analytics; e.g. "zeno-shipwreck").
"""

WEIRD_CAPSULES = [
    {"key": "diogenes-jar-sunlight",
     "hook_fact": "This philosopher lived in a giant ceramic jar in the middle of Athens.",
     "escalation": "Diogenes owned one cup — then saw a boy drink with his hands and threw the cup away. When Alexander the Great, the most powerful man alive, offered him anything he wanted, he said: 'Move. You're blocking my sunlight.'",
     "source_note": "Diogenes Laertius, Lives of Eminent Philosophers VI",
     "lesson_theme": "freedom through wanting less",
     "send_cta": "Send this to the friend who needs nothing and fears no one."},
    {"key": "socrates-standing-trance",
     "hook_fact": "Socrates once stood frozen in one spot for 24 hours straight — thinking.",
     "escalation": "During a military campaign, soldiers dragged their bedding outside to watch him. He stood through the night, solved whatever gripped his mind, greeted the sunrise, and walked off like nothing happened.",
     "source_note": "Plato, Symposium 220c-d",
     "lesson_theme": "depth of focus",
     "send_cta": "Send this to someone who can't sit with one thought for 5 minutes."},
    {"key": "diogenes-lamp-daylight",
     "hook_fact": "A man carried a lit lamp through Athens in broad daylight.",
     "escalation": "Asked what he was doing, Diogenes said: 'Looking for an honest human.' He held the lamp to people's faces all day. He reported finding none.",
     "source_note": "Diogenes Laertius, Lives VI.41",
     "lesson_theme": "honesty is rarer than daylight",
     "send_cta": "Send this to the most honest person you know. They'll get it."},
    {"key": "pythagoras-bean-taboo",
     "hook_fact": "Pythagoras — the triangle guy — banned his followers from touching beans.",
     "escalation": "The mathematical genius ran a secret society with rules like 'never eat beans' and 'don't pick up what has fallen.' Ancient sources say he'd rather be caught than cross a bean field.",
     "source_note": "Diogenes Laertius, Lives VIII; Iamblichus",
     "lesson_theme": "even geniuses guard strange disciplines",
     "send_cta": "Send this to your smartest friend with the weirdest habits."},
    {"key": "zeno-shipwreck",
     "hook_fact": "Zeno lost everything in a shipwreck — then thanked the sea.",
     "escalation": "A wealthy merchant, ruined in one storm, washed up in Athens, wandered into a bookshop, and founded Stoicism. He later said: 'I made a prosperous voyage when I suffered shipwreck.'",
     "source_note": "Diogenes Laertius, Lives VII.4",
     "lesson_theme": "catastrophe as redirection",
     "send_cta": "Send this to someone whose plan A just collapsed."},
    {"key": "chrysippus-laughing-donkey",
     "hook_fact": "An ancient philosopher reportedly laughed so hard at his own joke that he never got up again.",
     "escalation": "Chrysippus, who wrote 705 books of rigorous logic, saw a donkey eating figs, told someone to give it wine to wash them down, and laughed himself into collapse — the ancient account says he never recovered.",
     "source_note": "Diogenes Laertius, Lives VII.185",
     "lesson_theme": "seriousness and joy are not opposites",
     "send_cta": "Send this to the friend whose laugh could kill them."},
    {"key": "socrates-ugly-face",
     "hook_fact": "Socrates was ugly. Famously, insultingly ugly — and he agreed.",
     "escalation": "Snub nose, bulging eyes, a walk people mocked. The most beautiful minds in Athens followed him anyway. He joked his face proved wisdom lives somewhere other than looks.",
     "source_note": "Plato, Theaetetus 143e; Xenophon, Symposium",
     "lesson_theme": "substance beats appearance",
     "send_cta": "Send this to someone who forgets their face isn't their worth."},
    {"key": "diogenes-sold-into-slavery",
     "hook_fact": "Diogenes was sold into slavery — and interviewed his buyers.",
     "escalation": "Captured by pirates and put on the auction block, he pointed at a buyer and said 'Sell me to him. He needs a master.' He then ran the man's household and educated his sons.",
     "source_note": "Diogenes Laertius, Lives VI.74",
     "lesson_theme": "inner freedom no one can sell",
     "send_cta": "Send this to the freest person you know."},
    {"key": "epictetus-broken-leg",
     "hook_fact": "Epictetus' owner twisted his leg. The philosopher calmly narrated it breaking.",
     "escalation": "'You will break it,' the enslaved philosopher said. When it snapped: 'Did I not tell you?' He limped for life — and taught emperors that no one can chain a mind.",
     "source_note": "Origen, Contra Celsum VII.53 (ancient tradition)",
     "lesson_theme": "what remains yours under force",
     "send_cta": "Send this to someone going through what they didn't choose."},
    {"key": "marcus-aurelius-dawn-journal",
     "hook_fact": "A Roman emperor kept a private journal begging himself to get out of bed.",
     "escalation": "The most powerful man on Earth wrote, to no audience: 'At dawn, when you have trouble getting up — say: I am rising to do the work of a human being.' He struggled like you. Every morning.",
     "source_note": "Marcus Aurelius, Meditations V.1",
     "lesson_theme": "even emperors negotiate with the alarm",
     "send_cta": "Send this to the friend who snoozed four times today."},
    {"key": "diogenes-plucked-chicken",
     "hook_fact": "Diogenes attended a lecture, then plucked a chicken.",
     "escalation": "Plato defined a human as a 'featherless biped.' Diogenes burst into the academy holding a plucked chicken and announced: 'Behold — Plato's human!' Plato amended the definition.",
     "source_note": "Diogenes Laertius, Lives VI.40",
     "lesson_theme": "test grand claims against reality",
     "send_cta": "Send this to the friend who destroys bad arguments for fun."},
    {"key": "thales-well-and-olives",
     "hook_fact": "Thales fell into a well while staring at the stars.",
     "escalation": "The first philosopher of the West, mocked by a servant girl for studying the sky while missing the ground. Then he used his star knowledge to corner the olive-press market and got rich — to prove philosophers could.",
     "source_note": "Plato, Theaetetus 174a; Aristotle, Politics I.11",
     "lesson_theme": "vision needs footing",
     "send_cta": "Send this to your most head-in-the-clouds friend."},
    {"key": "cato-rehearses-poverty",
     "hook_fact": "Cato walked bareheaded in storms and wore no shoes in Rome.",
     "escalation": "One of Rome's richest senators deliberately practiced poverty — bad clothes, hard ground, plain food — so that if fortune ever took everything, it would find him already trained.",
     "source_note": "Plutarch, Life of Cato; Seneca, Letters 18",
     "lesson_theme": "rehearse loss to defeat fear",
     "send_cta": "Send this to someone terrified of losing what they have."},
    {"key": "socrates-daimonion-voice",
     "hook_fact": "Socrates heard a voice in his head his whole life — and obeyed it.",
     "escalation": "He called it his daimonion. It never told him what to do — only what NOT to do. It stayed silent the day he walked into the trial that ended his life. He took the silence as approval.",
     "source_note": "Plato, Apology 31d, 40a-c",
     "lesson_theme": "the quiet inner no",
     "send_cta": "Send this to someone who ignored their gut and regrets it."},
    {"key": "diogenes-begs-statues",
     "hook_fact": "A philosopher begged statues for money — on purpose, in public.",
     "escalation": "Asked why, Diogenes said: 'To practice being refused.' He rehearsed rejection daily until no human 'no' could touch him.",
     "source_note": "Diogenes Laertius, Lives VI.49",
     "lesson_theme": "rejection-proofing yourself",
     "send_cta": "Send this to the friend who's scared to ask."},
    {"key": "seneca-scheduled-poverty",
     "hook_fact": "Seneca — one of Rome's richest men — scheduled days of poverty.",
     "escalation": "Silk-wealthy, he'd set aside days to eat scraps and wear rags, asking one question the whole time: 'Is THIS what I was afraid of?' The answer kept being no.",
     "source_note": "Seneca, Letters to Lucilius 18",
     "lesson_theme": "fear shrinks when rehearsed",
     "send_cta": "Send this to someone whose fear is running the show."},
    {"key": "socrates-refuses-escape",
     "hook_fact": "Socrates refused to escape prison — his friends had already bribed the guards.",
     "escalation": "The door was effectively open. Crito begged. Socrates asked one question: 'If I flee the laws when they turn against me, was I ever just — or only lucky?' He stayed. He drank the hemlock.",
     "source_note": "Plato, Crito",
     "lesson_theme": "principles cost or they're decoration",
     "send_cta": "Send this to the most principled person you know."},
    {"key": "heraclitus-mountain-solitude",
     "hook_fact": "Heraclitus said you can't step in the same river twice — then chose to live in a stable.",
     "escalation": "The philosopher of change despised the crowds of Ephesus, retreated to the mountains, and reportedly lived on grasses and plants rather than trade his solitude for their politics.",
     "source_note": "Diogenes Laertius, Lives IX",
     "lesson_theme": "everything flows; choose your current",
     "send_cta": "Send this to the friend who's never the same person twice."},
    {"key": "aristippus-king-spit",
     "hook_fact": "Aristippus let a king spit in his face — and shrugged.",
     "escalation": "'Fishermen endure seawater to catch small fish,' he said. 'I endure spray to catch a big one.' The same man, watching Diogenes wash lentils: 'If you flattered kings, you wouldn't eat lentils.' Diogenes: 'If you ate lentils, you wouldn't flatter kings.'",
     "source_note": "Diogenes Laertius, Lives II.67-68",
     "lesson_theme": "every lifestyle has a price tag",
     "send_cta": "Send this to someone deciding what they're willing to pay."},
    {"key": "anaxagoras-mortal-sons",
     "hook_fact": "Anaxagoras was told he'd lost both his sons. He said only: 'I knew I had begotten mortals.'",
     "escalation": "Not coldness — preparation. He'd spent years rehearsing the truth everyone avoids, so grief found him standing. The ancients called it the discipline nobody wants until the day everybody needs it.",
     "source_note": "Diogenes Laertius, Lives II.13; Cicero, Tusculan Disputations III",
     "lesson_theme": "premeditatio malorum",
     "send_cta": "Send this to someone strong enough to hear it."},

    {"key": "cleanthes-water-by-night",
     "hook_fact": "One of history's most influential philosophers spent his nights hauling water for wages.",
     "escalation": "Cleanthes had almost no money, so he worked as a water-carrier by night just to afford Zeno's lectures by day. Athens grew suspicious of how he survived and hauled him before a council to explain his income — his humble ledger of labor won him praise instead of suspicion. He later ran the entire Stoic school as its second head.",
     "source_note": "Diogenes Laertius, Lives VII.168-170",
     "lesson_theme": "quiet labor behind visible greatness",
     "send_cta": "Send this to the friend working a night shift to fund their real goal."},
    {"key": "hipparchia-dowry-philosophy",
     "hook_fact": "A wealthy young woman turned down every rich suitor in Athens for a homeless philosopher.",
     "escalation": "Hipparchia came from money. Crates owned nothing but a cloak and a walking stick. She chose him anyway, adopted his rough Cynic life in public, and debated other philosophers in the open marketplace at a time women almost never spoke there.",
     "source_note": "Diogenes Laertius, Lives VI.96-98",
     "lesson_theme": "choosing substance over security",
     "send_cta": "Send this to the friend who picked the harder, truer option."},
    {"key": "crates-door-opener",
     "hook_fact": "A philosopher earned the nickname 'the door-opener' for walking into strangers' homes uninvited.",
     "escalation": "Crates would let himself into any household in Athens to settle arguments and counsel families, welcomed because his advice was that good. People started leaving their doors open for him on purpose.",
     "source_note": "Diogenes Laertius, Lives VI.86",
     "lesson_theme": "earning trust through consistent value",
     "send_cta": "Send this to the friend everyone calls first when things go wrong."},
    {"key": "socrates-leon-of-salamis",
     "hook_fact": "Ordered to help seize an innocent man, Socrates just went home instead.",
     "escalation": "Under a brutal ruling council, five citizens were told to fetch Leon of Salamis on false grounds, implicating them all. Four obeyed. Socrates simply walked home. He said later it might have cost him his life if the council hadn't fallen first.",
     "source_note": "Plato, Apology 32c-d",
     "lesson_theme": "quiet refusal as courage",
     "send_cta": "Send this to the friend who won't go along just to stay comfortable."},
    {"key": "cato-marches-on-foot",
     "hook_fact": "A Roman leader made his soldiers ride while he walked the entire march himself.",
     "escalation": "Cato had a horse. He walked anyway, mile after mile, alongside the soldiers on foot, only mounting briefly to check on the ones who were struggling before getting off again.",
     "source_note": "Plutarch, Life of Cato the Younger",
     "lesson_theme": "leadership by shared discomfort",
     "send_cta": "Send this to the leader who never asks more of others than of themselves."},
    {"key": "cato-refuses-spoils",
     "hook_fact": "After a hard campaign, Cato was offered a share of the plunder. He took none of it.",
     "escalation": "Commanders traditionally pocketed a cut of whatever was seized. Cato left it all for the public treasury and went home with exactly what he came with — nothing extra.",
     "source_note": "Plutarch, Life of Cato the Younger",
     "lesson_theme": "integrity when no one would notice",
     "send_cta": "Send this to the friend who'd never take the extra that's owed to no one."},
    {"key": "musonius-rufus-gyaros",
     "hook_fact": "Exiled to a barren island with nothing on it, a philosopher just kept teaching.",
     "escalation": "Musonius Rufus was banished to the island of Gyaros — no city, no library, barely any water. Ancient accounts say students sailed out just to sit on the rocks and listen to him lecture anyway.",
     "source_note": "Philostratus, Life of Apollonius VII.16; fragments of Musonius Rufus",
     "lesson_theme": "purpose that doesn't need an audience or a stage",
     "send_cta": "Send this to someone who'd keep doing the work with nobody watching."},
    {"key": "seneca-seasickness-essay",
     "hook_fact": "A famous Stoic philosopher wrote an entire essay about how seasick he got on a boat.",
     "escalation": "Seneca boarded a ship for a short trip and was miserably sick within minutes — all his training didn't stop his stomach. He wrote to a friend that he'd rather walk the whole way, admitting some things philosophy just has to sit through, not fix.",
     "source_note": "Seneca, Letters to Lucilius 53",
     "lesson_theme": "wisdom doesn't erase discomfort, it outlasts it",
     "send_cta": "Send this to the friend who gets carsick but still shows up."},
    {"key": "diogenes-barrel-rolling",
     "hook_fact": "While a city prepared for a coming siege, one man rolled a barrel up and down a hill for no reason.",
     "escalation": "Everyone in Corinth was suddenly busy, building, drilling, fortifying. Diogenes, with nothing to contribute, started rolling his barrel up a hill and back down, over and over, so he wouldn't be the only idle one in a city acting busy.",
     "source_note": "Lucian, How to Write History 3 (on Diogenes at Corinth)",
     "lesson_theme": "mocking performative busyness",
     "send_cta": "Send this to the friend who can spot fake urgency a mile away."},
    {"key": "diogenes-eats-in-marketplace",
     "hook_fact": "A philosopher deliberately ate his lunch in the middle of the busiest marketplace in Athens.",
     "escalation": "Eating in public was considered shameful, a private act done at home. Diogenes sat in the agora and ate anyway, arguing that if it's not wrong to eat, it's not wrong to eat anywhere. Crowds gathered just to watch him do it.",
     "source_note": "Diogenes Laertius, Lives VI.58",
     "lesson_theme": "questioning shame that has no real reason",
     "send_cta": "Send this to the friend who ignores rules that don't actually make sense."},
    {"key": "antisthenes-torn-cloak",
     "hook_fact": "A philosopher wore a deliberately ripped cloak to look humble — and got called out for it.",
     "escalation": "Antisthenes tore holes in his cloak to display his rejection of luxury. Socrates spotted him showing it off and said: 'I can see your vanity through the holes in your cloak.'",
     "source_note": "Diogenes Laertius, Lives VI.8",
     "lesson_theme": "humility can become its own vanity",
     "send_cta": "Send this to the friend who's a little too proud of being humble."},
    {"key": "heraclitus-dice-with-children",
     "hook_fact": "A famous philosopher was found playing dice with kids instead of doing politics.",
     "escalation": "Ephesus wanted Heraclitus to help write their laws. He refused, and was found in the temple playing knucklebones with children instead. Asked why, he said this was more worthwhile than running the city alongside corrupt men.",
     "source_note": "Diogenes Laertius, Lives IX.3",
     "lesson_theme": "walking away from broken systems",
     "send_cta": "Send this to the friend who quit the group project on principle."},
    {"key": "aristippus-shipwreck-wealth",
     "hook_fact": "Shipwrecked with nothing, a philosopher spotted marks in the sand and said 'good news.'",
     "escalation": "Washed ashore with the rest of the cargo lost, Aristippus noticed geometric diagrams drawn in the sand and told his companions to cheer up, this was a civilized place. He later said the only wealth worth having is the kind that swims ashore with you.",
     "source_note": "Vitruvius, On Architecture VI, preface",
     "lesson_theme": "what you carry inside you can't be lost",
     "send_cta": "Send this to the friend who'd be fine starting over from zero."},
    {"key": "epicurus-pot-of-cheese",
     "hook_fact": "One of history's most famous pleasure-philosophers lived on bread and water — on purpose.",
     "escalation": "Epicurus, whose name became shorthand for indulgence, actually ate plain barley bread daily and called it enough for a full life. His idea of a splurge was writing to a friend asking for a small pot of cheese so he could 'feast when I like.'",
     "source_note": "Diogenes Laertius, Lives X.11",
     "lesson_theme": "pleasure recalibrated by simplicity",
     "send_cta": "Send this to the friend whose treat-yourself is embarrassingly modest."},
    {"key": "marcus-aurelius-sells-furniture",
     "hook_fact": "An emperor sold his own palace furniture instead of raising taxes on his people.",
     "escalation": "Marcus Aurelius needed money fast for a costly campaign. Rather than squeeze the public, he auctioned off imperial furniture, jewelry, and silk robes from the palace, and let ordinary citizens buy them back later if they wanted.",
     "source_note": "Historia Augusta, Life of Marcus Aurelius 17; Cassius Dio, Roman History LXXII.32",
     "lesson_theme": "leaders absorbing cost instead of passing it down",
     "send_cta": "Send this to the boss who'd never make the team cover their shortfall."},
    {"key": "epictetus-stolen-lamp",
     "hook_fact": "A thief broke in and stole an iron lamp. The philosopher who owned it was almost relieved.",
     "escalation": "Epictetus, who owned almost nothing valuable, lost his one iron lamp to a burglar. He said the thief paid a price for it he didn't realize, his own honesty, for a lamp. Epictetus went out and bought a cheap clay one instead and slept fine.",
     "source_note": "Epictetus, Fragments (via Stobaeus)",
     "lesson_theme": "what a theft actually costs the thief",
     "send_cta": "Send this to the friend who never lets small losses ruin their day."},
    {"key": "zeno-two-ears-one-mouth",
     "hook_fact": "A philosopher's whole discipline could be summed up in one line about ears and mouths.",
     "escalation": "Zeno reportedly taught that nature gave humans two ears and one mouth so they'd listen twice as much as they speak. He ran his own school by the same ratio, famously short on words, long on listening.",
     "source_note": "Diogenes Laertius, Lives VII (ancient tradition on Zeno)",
     "lesson_theme": "listening as a discipline, not an accident",
     "send_cta": "Send this to the friend who talks less and somehow knows more."},
    {"key": "cato-wears-odd-colors",
     "hook_fact": "A respected public figure walked around Rome in colors everyone considered embarrassing.",
     "escalation": "Cato deliberately wore dark, unfashionable clothing while everyone around him dressed to impress, practicing being laughed at so public opinion could never control him again.",
     "source_note": "Plutarch, Life of Cato the Younger",
     "lesson_theme": "immunizing yourself against ridicule",
     "send_cta": "Send this to the friend who doesn't dress for anyone else's approval."},
    {"key": "socrates-dawn-dancing",
     "hook_fact": "One of history's greatest minds was caught dancing alone at home in his old age.",
     "escalation": "A guest found Socrates dancing by himself at dawn and asked why. He said it kept his body as fit as his mind, and that he saw nothing shameful about a grown man improving his health, in private, however that looked.",
     "source_note": "Xenophon, Symposium 2.16-19",
     "lesson_theme": "not caring how self-improvement looks",
     "send_cta": "Send this to the friend who works out in the weirdest way and doesn't care."},
    {"key": "bias-of-priene-carry-everything",
     "hook_fact": "As his city burned, one man walked out carrying nothing while everyone else grabbed all they could.",
     "escalation": "When enemies sacked Priene, residents fled loaded down with valuables. Bias walked out empty-handed. Asked why, he said: 'I carry all my belongings within me.'",
     "source_note": "Cicero, Paradoxa Stoicorum I",
     "lesson_theme": "what can't be taken from you",
     "send_cta": "Send this to the friend who'd be fine if they lost everything tomorrow."},
    {"key": "stilpo-lost-nothing-of-my-own",
     "hook_fact": "A conquering general leveled his entire city, and the philosopher living there said he'd lost nothing.",
     "escalation": "After Demetrius destroyed Megara and Stilpo's house along with it, Demetrius asked if he'd lost anything in the ruin. Stilpo answered: no, conquest can plunder a city, not a mind. Demetrius was so struck he ordered no further harm to the philosopher's home.",
     "source_note": "Seneca, On the Constancy of the Wise Man 5",
     "lesson_theme": "identity beyond possessions",
     "send_cta": "Send this to the friend who'd stay themselves after losing everything."},
    {"key": "diogenes-defaced-currency-origin",
     "hook_fact": "Before he was a philosopher, this man's family business got him run out of his hometown.",
     "escalation": "Diogenes' father ran the local mint at Sinope and was caught tampering with the coinage. Diogenes fled to Delphi, where the oracle told him to 'deface the currency.' He spent the rest of his life figuring out it meant defying fake social value, not literal coins.",
     "source_note": "Diogenes Laertius, Lives VI.20-21",
     "lesson_theme": "reinterpreting a disaster as a calling",
     "send_cta": "Send this to the friend who turned a family mess into a whole new life."},
    {"key": "diogenes-mouse-lesson",
     "hook_fact": "A philosopher's entire worldview changed after watching a mouse for a few minutes.",
     "escalation": "Diogenes noticed a mouse that wasn't looking for a bed, wasn't afraid of the dark, and didn't chase anything considered a luxury. He decided if a mouse could be that adaptable, so could he, and reshaped his whole life around needing almost nothing.",
     "source_note": "Diogenes Laertius, Lives VI.22",
     "lesson_theme": "adaptability as a taught skill",
     "send_cta": "Send this to the friend who can sleep anywhere and be fine."},
    {"key": "xanthippe-water-thunder",
     "hook_fact": "Socrates' wife once dumped a bucket of water on his head mid-argument.",
     "escalation": "After Xanthippe scolded him loudly and he stayed calm, she poured water over him. He just laughed and said: 'After the thunder, naturally comes the rain.'",
     "source_note": "Diogenes Laertius, Lives II.36-37",
     "lesson_theme": "humor defusing a fight",
     "send_cta": "Send this to the friend who never loses their cool in an argument."},
    {"key": "crates-gives-away-fortune",
     "hook_fact": "A rich man gave away his entire fortune just to become a homeless philosopher.",
     "escalation": "Crates came from serious wealth. He converted it all to cash, distributed it to the citizens of Thebes, and walked off with a cloak and a staff, saying money had been getting in the way of the life he actually wanted.",
     "source_note": "Diogenes Laertius, Lives VI.87-88",
     "lesson_theme": "choosing freedom over comfort",
     "send_cta": "Send this to the friend who'd quit a great salary for the right reason."},
    {"key": "seneca-nightly-self-review",
     "hook_fact": "One of Rome's most powerful men interrogated himself every single night before bed.",
     "escalation": "Seneca reviewed his entire day after the lights went out, asking himself what habit he'd cured, what fault he'd resisted, in what way he was better. He borrowed the habit from the Pythagoreans and never skipped a night.",
     "source_note": "Seneca, On Anger III.36",
     "lesson_theme": "daily self-audit as discipline",
     "send_cta": "Send this to the friend who journals every single night."},
    {"key": "diogenes-citizen-of-the-world",
     "hook_fact": "Asked which city he was from, a philosopher gave an answer nobody in Athens had ever heard.",
     "escalation": "Most Greeks defined themselves entirely by their home city. Diogenes, asked where he was from, said simply: 'I am a citizen of the world.' It's the first recorded use of the idea now called cosmopolitanism.",
     "source_note": "Diogenes Laertius, Lives VI.63",
     "lesson_theme": "identity bigger than geography",
     "send_cta": "Send this to the friend who feels at home literally anywhere."},
    {"key": "epicurus-frees-his-household",
     "hook_fact": "A philosopher's final legal document quietly did something almost nobody did in his era.",
     "escalation": "In his will, Epicurus arranged for members of his household who'd worked for him to be freed. He treated the people in his philosophical community, regardless of status, as equally capable of the good life he taught.",
     "source_note": "Diogenes Laertius, Lives X.10, X.21",
     "lesson_theme": "practicing your values where it costs something",
     "send_cta": "Send this to the friend who treats everyone the exact same way."},
    {"key": "zeno-declines-honors",
     "hook_fact": "Athens tried to give a philosopher a golden crown and a statue. He basically shrugged.",
     "escalation": "The city voted Zeno the keys to its gates and a gold crown for his character, and later a bronze statue, all preserved in the honorary decree. He kept living exactly as plainly as before, letting his students' work speak instead of the bronze.",
     "source_note": "Diogenes Laertius, Lives VII.6",
     "lesson_theme": "staying unchanged by recognition",
     "send_cta": "Send this to the friend who'd stay the same after going viral."},
    {"key": "diogenes-exile-made-me",
     "hook_fact": "A man mocked a philosopher for being exiled from his hometown. The philosopher agreed and thanked him.",
     "escalation": "Someone reproached Diogenes for having been banished from Sinope. He replied it was exactly that exile, that loss of everything familiar, that had made him a philosopher in the first place.",
     "source_note": "Diogenes Laertius, Lives VI.49",
     "lesson_theme": "reframing loss as origin",
     "send_cta": "Send this to the friend whose worst year became their best decision."},
    {"key": "socrates-delphi-wisest-man",
     "hook_fact": "A priestess told a friend Socrates was the wisest man alive, and it nearly ruined his life.",
     "escalation": "The Oracle at Delphi told Socrates' friend that no one was wiser than Socrates. Confused, since he felt he knew nothing, Socrates spent years questioning every 'expert' in Athens to test the claim, and made enough enemies doing it to eventually stand trial for it.",
     "source_note": "Plato, Apology 21a-23b",
     "lesson_theme": "testing a compliment instead of accepting it",
     "send_cta": "Send this to the friend who fact-checks every compliment they get."},
    {"key": "plato-anger-delegated-punishment",
     "hook_fact": "Furious at a member of his household, a philosopher refused to handle it himself.",
     "escalation": "Plato, angry enough that he didn't trust his own judgment, asked a friend to handle the matter instead, saying: 'I might not do it with restraint, because I am angry.'",
     "source_note": "Seneca, On Anger III.12",
     "lesson_theme": "knowing when you're not fit to decide",
     "send_cta": "Send this to the friend who waits until they've cooled off to respond."},
    {"key": "solon-call-no-life-happy",
     "hook_fact": "A king showed off his gold to a philosopher expecting to be called the happiest man alive. He wasn't.",
     "escalation": "Croesus, one of the richest kings in the ancient world, asked Solon who was the happiest man he'd ever met, fishing for his own name. Solon named ordinary people instead and warned that no life can be called happy until you see how the whole story ends.",
     "source_note": "Herodotus, Histories I.30-33",
     "lesson_theme": "wealth isn't the final verdict on a life",
     "send_cta": "Send this to the friend who's chasing a number instead of a life."},
    {"key": "aristotle-freedom-from-fear-of-law",
     "hook_fact": "Asked what philosophy actually gave him, one of history's greatest minds gave a strange answer.",
     "escalation": "Aristotle was asked what he had gained from philosophy. He said: doing willingly what others only do because they're afraid of getting caught.",
     "source_note": "Diogenes Laertius, Lives V.20",
     "lesson_theme": "internal vs external motivation",
     "send_cta": "Send this to the friend with real integrity when no one's watching."},
]

WEIRD_HYPOTHETICALS = [
    {"key": "hyp-phone-testify",
     "hook_fact": "If your phone could testify about your week, would you delete it before the trial?",
     "escalation": "Every unlock logged. Every 2am scroll on record. Every 'just five minutes' entered as evidence. The prosecution rests.",
     "source_note": "hypothetical",
     "lesson_theme": "your attention is the testimony",
     "send_cta": "Send this to the friend whose phone would snitch hardest.",
     "hypothetical": True},
    {"key": "hyp-meet-past-self",
     "hook_fact": "Imagine you met yourself from 5 years ago — and they refused to shake your hand.",
     "escalation": "Not because you failed. Because you quietly gave up the exact things they were fighting for, and called it 'being realistic.'",
     "source_note": "hypothetical",
     "lesson_theme": "audit the trade-offs",
     "send_cta": "Send this to someone their younger self would still be proud of.",
     "hypothetical": True},
    {"key": "hyp-complaint-hour-cost",
     "hook_fact": "Suppose every complaint you spoke cost you one hour of life.",
     "escalation": "Some people in your group chat would be gone by Thursday. The Stoics ran this exact accounting — they just used attention instead of hours.",
     "source_note": "hypothetical",
     "lesson_theme": "complaint is spent attention",
     "send_cta": "Send this to the group chat. You know which one.",
     "hypothetical": True},
    {"key": "hyp-gratitude-inventory",
     "hook_fact": "What if you woke up tomorrow with only the things you thanked someone for yesterday?",
     "escalation": "Most people would wake up with nothing but wifi and coffee. The ancients called gratitude an inventory, not a feeling.",
     "source_note": "hypothetical",
     "lesson_theme": "gratitude as inventory",
     "send_cta": "Send this to someone you never actually thanked.",
     "hypothetical": True},
    {"key": "hyp-habit-mirror",
     "hook_fact": "Imagine a mirror that showed your habits instead of your face.",
     "escalation": "You'd see the 6 hours of scrolling standing behind you. The workout you skipped sitting on your shoulders. Nobody would own one. Everybody needs one.",
     "source_note": "hypothetical",
     "lesson_theme": "habits are the real reflection",
     "send_cta": "Send this to the friend brave enough to look.",
     "hypothetical": True},
    {"key": "hyp-silence-currency",
     "hook_fact": "If silence cost money, how much would your mind owe by noon?",
     "escalation": "Every notification answered like a debt collector. The Stoics ran the ledger differently: attention paid IN is the only interest that compounds.",
     "source_note": "hypothetical",
     "lesson_theme": "attention as currency",
     "send_cta": "Send this to someone who hasn't had a quiet hour in weeks.",
     "hypothetical": True},
]


def pick_weird(row_number: int | None) -> dict:
    """Deterministic weird pick: 3 true capsules to every 1 hypothetical."""
    n = row_number or 0
    if n % 4 == 3:
        return WEIRD_HYPOTHETICALS[(n // 4) % len(WEIRD_HYPOTHETICALS)]
    idx = (n - n // 4) % len(WEIRD_CAPSULES)
    return WEIRD_CAPSULES[idx]
