#!/usr/bin/env python3
"""Generate hyperframes/css/moods.css from remotion/src/styles/theme.ts MOOD_PALETTES.

Run once after theme.ts changes (rare). Checked in for parity guarantee.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path


def _panic(msg: str) -> None:
    print(msg, file=sys.stderr)
    sys.exit(1)


def parse_theme_ts(path: Path) -> dict[str, dict[str, str | list[str] | bool]]:
    text = path.read_text(encoding="utf-8")

    # Find the MOOD_PALETTES object literal
    match = re.search(r"export const MOOD_PALETTES:.*?= \{(.*?)\};", text, re.DOTALL)
    if not match:
        _panic(f"Could not find MOOD_PALETTES in {path}")

    block = match.group(1)
    moods: dict[str, dict[str, str | list[str] | bool]] = {}

    # Split into top-level mood entries:  moodName: { ... },
    # Use a regex that finds each mood key and its inner object.
    for m in re.finditer(r"(\w+):\s*\{(.*?)\},?\s*(?=\w+:|\Z)", block, re.DOTALL):
        mood_name = m.group(1)
        inner = m.group(2)

        data: dict[str, str | list[str] | bool] = {}

        # bg: ["#...", "#...", "#..."]
        bg_match = re.search(r'bg:\s*\["(.*?)",\s*"(.*?)",\s*"(.*?)"\]', inner)
        if bg_match:
            data["bg"] = [bg_match.group(1), bg_match.group(2), bg_match.group(3)]

        # text: "#..."
        text_match = re.search(r'text:\s*"(.*?)"', inner)
        if text_match:
            data["text"] = text_match.group(1)

        # stroke: "#..."
        stroke_match = re.search(r'stroke:\s*"(.*?)"', inner)
        if stroke_match:
            data["stroke"] = stroke_match.group(1)

        # accent: "#..."
        accent_match = re.search(r'accent:\s*"(.*?)"', inner)
        if accent_match:
            data["accent"] = accent_match.group(1)

        # glow: "#..."
        glow_match = re.search(r'glow:\s*"(.*?)"', inner)
        if glow_match:
            data["glow"] = glow_match.group(1)

        # particles: ["#...", "#...", "#..."]
        particles_match = re.search(r'particles:\s*\["(.*?)",\s*"(.*?)",\s*"(.*?)"\]', inner)
        if particles_match:
            data["particles"] = [particles_match.group(1), particles_match.group(2), particles_match.group(3)]

        # dark: true/false
        dark_match = re.search(r'dark:\s*(true|false)', inner)
        if dark_match:
            data["dark"] = dark_match.group(1) == "true"

        moods[mood_name] = data

    return moods


def emit_css(moods: dict[str, dict[str, str | list[str] | bool]], out: Path) -> None:
    lines = [
        "/* Generated by scripts/sync_moods.py — do NOT edit by hand. */",
        "/* Source of truth: remotion/src/styles/theme.ts MOOD_PALETTES */",
        "",
    ]
    for mood_name, data in moods.items():
        lines.append(f'[data-mood="{mood_name}"] {{')
        bg = data.get("bg", ["#000", "#000", "#000"])
        lines.append(f"  --bg-outer: {bg[0]};")
        lines.append(f"  --bg-core: {bg[1]};")
        lines.append(f"  --bg-outer2: {bg[2]};")
        lines.append(f"  --text: {data.get('text', '#fff')};")
        lines.append(f"  --stroke: {data.get('stroke', '#000')};")
        lines.append(f"  --accent: {data.get('accent', '#fff')};")
        lines.append(f"  --glow: {data.get('glow', '#fff')};")
        particles = data.get("particles", ["#fff", "#fff", "#fff"])
        lines.append(f"  --particle-1: {particles[0]};")
        lines.append(f"  --particle-2: {particles[1]};")
        lines.append(f"  --particle-3: {particles[2]};")
        is_dark = "1" if data.get("dark", True) else "0"
        lines.append(f"  --is-dark: {is_dark};")
        lines.append("}")
        lines.append("")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    repo_root = Path(__file__).parent.parent
    theme_path = repo_root / "remotion" / "src" / "styles" / "theme.ts"
    out_path = repo_root / "hyperframes" / "css" / "moods.css"

    if not theme_path.exists():
        _panic(f"theme.ts not found: {theme_path}")

    moods = parse_theme_ts(theme_path)
    if not moods:
        _panic("No moods parsed from theme.ts")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    emit_css(moods, out_path)
    print(f"Synced {len(moods)} moods -> {out_path}")


if __name__ == "__main__":
    main()
